#config_version=6

mode:
  start_events: start_mode_banana_load
  stop_events: stop_mode_banana_load,start_mode_banana_bend
  priority: 200

# modes/banana_load/config/banana_load.yaml

shots:
  shot_l_load_start:
    show_tokens:
      leds: l_load_state
    profile: sp_banana_load_profile_on
    hit_events: mode_banana_load_started

shot_profiles:
  sp_banana_load_profile_flash:
    states:
      - name: off
        show: off
      - name: on
        show: sh_led_flash
        show_tokens:
          color: white
  sp_banana_load_profile_on:
    states:
      - name: off
        show: off
      - name: on
        show: sh_insert_on
        show_tokens:
          color: tt_red

event_player:
  mode_banana_load_started{device.counters.co_banana_belt_count.value>=current_player.pv_unbended_bananas_to_complete}: start_mode_banana_bend
  mode_banana_load_started: disable_lock_diverter, disable_top_left_gate_diverter