#config_version=6

mode:
  start_events: start_mode_banana_load
  stop_events: stop_mode_banana_load,start_mode_banana_bend
  priority: 200

# modes/banana_load/config/banana_load.yaml

light_player:
  mode_banana_load_started:
    l_led_load_state: tt_red
  mode_banana_load_stopping:
    l_led_load_state: off

event_player:
  mode_banana_load_started{device.counters.banana_belt_count.value>=current_player.unbended_bananas_to_complete}: start_mode_banana_bend