#config_version=6

mode:
  start_events: start_mode_banana_bend
  stop_events: stop_mode_banana_bend
  priority: 200

# modes/banana_belt/config/banana_bend.yaml

shots:
  shot_l_bend_start:
    show_tokens:
      leds: l_led_bend_bananas
    profile: banana_bend_profile_flash
    hit_events: mode_banana_bend_started
  shot_l_bend_mode_start:
    show_tokens:
        leds: l_led_bend_state
    profile: banana_bend_profile_on
    hit_events: mode_banana_bend_started

shot_profiles:
  banana_bend_profile_flash:
    states:
      - name: off
        show: off
      - name: on
        show: led_flash
        show_tokens:
          color: white
  banana_bend_profile_on:
    states:
      - name: off
        show: off
      - name: on
        show: insert_on
        show_tokens:
          color: tt_red



