#config_version=6

hardware:
   platform: opp
   driverboards: gen2

opp:
   ports: /dev/ttyACM0, /dev/ttyACM1

config:
- hardware.yaml

player_vars:
  bonus_multiplier:
    initial_value: 1
  base_bonus:
    initial_value: 0

modes:
- attract
- base
- bumper
- slingshot

ball_devices:
    bd_trough:
        ball_switches: s_ball_trough_1,s_ball_trough_2,s_ball_trough_3
        jam_switch: s_ball_trough_jam
        eject_coil: c_outhole
        tags: trough, home, drain, home
        eject_coil_jam_pulse: 15ms
        eject_timeouts: 3s
            
playfields:
  playfield:
    tags: default
    default_source_device: bd_trough
    enable_ball_search: True
    ball_search_timeout: 45s
    ball_search_wait_after_iteration: 30s
    ball_search_interval: 250ms

virtual_platform_start_active_switches: s_ball_trough_1, s_ball_trough_2, s_ball_trough_3, s_bank3_down

logging:
  console:
    bcp: none
    bcp_client: none
    bcp_interface: none
    bcp_server: none
  file:
    bcp: none
    bcp_client: none
    bcp_interface: none
    bcp_server: none

bcp:
  debug: false
  warning: false
  
named_colors:
   tt_white:   [255,250,240]
   tt_nwhite:  [255,240,200]
   tt_wwhite:  [255,230,170]
   tt_yellow:  [255,220,  0]
   tt_orange:  [255,110,  0]
   tt_blue:    [ 15, 72,255]
   tt_ltblue:  [ 30,144,255]
   tt_red:     [255,  0,  0]
   tt_green:   [  0,255,  0]
   tt_magenta: [255,  0,255]