#config_version=6

coils:
    c_outhole:
       number: 0-0-7
       default_pulse_ms: 22
       default_pulse_power: 0.55
       default_hold_power: 0.075
    c_flipper_left:
        number: 0-0-14
        #allow_enable: true
        default_hold_power: 0.08
        default_pulse_power: 1.0
        default_pulse_ms: 35
    c_flipper_right:
        number: 0-0-13
        #allow_enable: true
        default_hold_power: 0.08
        default_pulse_power: 1.0
        default_pulse_ms: 35
    c_right_sling:
       number: 0-0-3
       default_pulse_ms: 22
       default_pulse_power: 0.55
       default_recycle: True
       platform_settings:
            recycle_factor: 4
    c_bump:
       number: 0-0-4
       default_pulse_ms: 22
       default_pulse_power: 0.55
       default_recycle: True
       platform_settings:
            recycle_factor: 1
        
switches:
    #Cabinet Switches
   s_start_button:
 #     number: 0-0-16
      number: 1-0-32
      tags: start
      ignore_window_ms: 500ms 
   s_left_flipper:
      number: 0-0-17
      tags: left_flipper
   s_right_flipper:
      number: 0-0-18
      tags: right_flipper
    #Playfield Switches (Matrix)
   s_launch_button:
      number: 1-0-33
   s_setup_button:
      number: 1-0-34
   s_plus_button:
      number: 1-0-35
   s_minus_button:
      number: 1-0-36
   s_enter_button:
      number: 1-0-37
   s_tilt:
      number: 1-0-38
      tags: tilt_warning
   s_coin_mech:
      number: 1-0-39
   s_red_monkey_target:
      number: 1-0-40
   s_bumper_done:
      number: 1-0-41    
   s_bank4_1:
      number: 1-0-42  
   s_bank4_2:
      number: 1-0-43  
   s_bank4_3:
      number: 1-0-44  
   s_bank4_4:
      number: 1-0-45  
   s_left_lane:
      number: 1-0-46  
   s_right_lane:
      number: 1-0-47  
   s_left_orbit:
      number: 1-0-48  
   s_right_orbit:
      number: 1-0-49  
   s_bank3_1:
      number: 1-0-50  
   s_bank3_2:
      number: 1-0-51  
   s_bank3_3:
      number: 1-0-52  
   s_right_mini_target:
      number: 1-0-53  
   s_left_mini_target:
      number: 1-0-54  
   s_spinner:
      number: 1-0-55  
   s_slingshot_done:
      number: 1-0-56  
   s_left_inlane:
      number: 1-0-57  
   s_right_inlane:
      number: 1-0-58  
   s_bank3_target:
      number: 1-0-59  
   s_bank3_down:
      number: 1-0-60  
   s_bank3_up:
      number: 1-0-61  


    #Playfield Switches (Direct)
   s_left_EOS:
      number: 0-0-1
   s_right_EOS:
      number: 0-0-2
   s_ball_trough_1:
      number: 0-0-8    
   s_ball_trough_2:
      number: 0-0-9   
   s_ball_trough_3:
      number: 0-0-10   
   s_ball_trough_jam:
      number: 0-0-11   
   s_bumper_spe:
      number: 0-0-16 
   s_slingshot_spe:
      number: 0-0-19 
   s_lock_1:
      number: 0-0-24 
   s_lock_2:
      number: 0-0-25 
   s_lock_3:
      number: 0-0-26 
   s_magnet_1:
      number: 0-0-27 
   s_magnet_2:
      number: 1-0-1 
   s_ramp_begin:
      number: 0-0-3

flippers:
  left_flipper:
        main_coil: c_flipper_left
        activation_switch: s_left_flipper
        eos_switch : s_left_EOS
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown
  right_flipper:
        main_coil: c_flipper_right
        activation_switch: s_right_flipper
        eos_switch : s_right_EOS
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown

autofire_coils:
    slingshot_right:
        coil: c_right_sling
        switch: s_slingshot_done
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown
    pop_bumper:
        coil: c_bump
        switch: s_bumper_done
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown

lights:
    l_Led_unbended_b_1:
        number: 0-0-0
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_1:
        previous: l_Led_unbended_b_1 #number: 0-0-0
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_2:
        previous: l_Led_bended_b_1 #number: 0-0-1
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_2:
        previous: l_Led_unbended_b_2 #number: 0-0-2
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_3:
        previous: l_Led_bended_b_2 #number: 0-0-3
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_3:
        previous: l_Led_unbended_b_3 #number: 0-0-4
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_4:
        previous: l_Led_bended_b_3 #number: 0-0-5
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_4:
        previous: l_Led_unbended_b_4 #number: 0-0-6
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_5:
        previous: l_Led_bended_b_4 #number: 0-0-7
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_5:
        previous: l_Led_unbended_b_5 #number: 0-0-8
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_6:
        previous: l_Led_bended_b_5 #number: 0-0-9
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_6:
        previous: l_Led_unbended_b_6 #number: 0-0-10
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_7:
        previous: l_Led_bended_b_6 #number: 0-0-11
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_7:
        previous: l_Led_unbended_b_7 #number: 0-0-12
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_8:
        previous: l_Led_bended_b_7 #number: 0-0-13
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_8:
        previous: l_Led_unbended_b_8 #number: 0-0-14
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_9:
        previous: l_Led_bended_b_8 #number: 0-0-15
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_9:
        previous: l_Led_unbended_b_9 #number: 0-0-16
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_10:
        previous: l_Led_bended_b_9 #number: 0-0-17
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_10:
        previous: l_Led_unbended_b_10 #number: 0-0-18
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_11:
        previous: l_Led_bended_b_10 #number: 0-0-19
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_11:
        previous: l_Led_unbended_b_11 #number: 0-0-20
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_12:
        previous: l_Led_bended_b_11 #number: 0-0-21
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_12:
        previous: l_Led_unbended_b_12 #number: 0-0-22
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_13:
        previous: l_Led_bended_b_12 #number: 0-0-23
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_13:
        previous: l_Led_unbended_b_13 #number: 0-0-24
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_14:
        previous: l_Led_bended_b_13 #number: 0-0-25
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_14:
        previous: l_Led_unbended_b_14 #number: 0-0-26
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_15:
        previous: l_Led_bended_b_14 #number: 0-0-27
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_15:
        previous: l_Led_unbended_b_15 #number: 0-0-28
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_16:
        previous: l_Led_bended_b_15 #number: 0-0-29
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_16:
        previous: l_Led_unbended_b_16 #number: 0-0-30
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_17:
        previous: l_Led_bended_b_16 #number: 0-0-31
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_17:
        previous: l_Led_unbended_b_17 #number: 0-0-32
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_18:
        previous: l_Led_bended_b_17 #number: 0-0-33
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_18:
        previous: l_Led_unbended_b_18 #number: 0-0-34
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_19:
        previous: l_Led_bended_b_18 #number: 0-0-35
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_19:
        previous: l_Led_unbended_b_19 #number: 0-0-36
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_20:
        previous: l_Led_bended_b_19 #number: 0-0-37
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_20:
        previous: l_Led_unbended_b_20 #number: 0-0-38
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_21:
        previous: l_Led_bended_b_20 #number: 0-0-39
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_21:
        previous: l_Led_unbended_b_21 #number: 0-0-40
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_22:
        previous: l_Led_bended_b_21 #number: 0-0-41
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_22:
        previous: l_Led_unbended_b_22 #number: 0-0-42
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_23:
        previous: l_Led_bended_b_22 #number: 0-0-43
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_23:
        previous: l_Led_unbended_b_23 #number: 0-0-444
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_24:
        previous: l_Led_bended_b_23 #number: 0-0-45
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_24:
        previous: l_Led_unbended_b_24 #number: 0-0-46
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_unbended_b_25:
        previous: l_Led_bended_b_24 #number: 0-0-47
        type: grb
        subtype: led
        tags: banana_belt
    l_Led_bended_b_25:
        previous: l_Led_unbended_b_25 #number: 0-0-48
        type: grb
        subtype: led
        tags: banana_belt


# keyboard:
#    1:
#      event: led_off
#    2:
#      event: led_code
#    3:
#      event: led_name
#    4:
#      event: group_light
#    5:
#      event: led_fade
     
ball_devices:
    bd_trough:
        ball_switches: s_ball_trough_1,s_ball_trough_2,s_ball_trough_3
        jam_switch: s_ball_trough_jam
        eject_coil: c_outhole
        tags: trough, home, drain, home
        eject_coil_jam_pulse: 15ms
        debug: true
            
playfields:
  playfield:
    tags: default
    default_source_device: bd_trough
    enable_ball_search: True
    ball_search_timeout: 45s
    ball_search_wait_after_iteration: 30s
    ball_search_interval: 250ms

virtual_platform_start_active_switches: s_ball_trough_1, s_ball_trough_2, s_ball_trough_3, s_bank3_down

machine:
    balls_installed: 3

game:
    balls_per_game: 3
    max_players: 4