#config_version=6

coils:
    c_outhole:
       number: 0-0-7
       default_pulse_ms: 22
       default_pulse_power: 0.55
       default_hold_power: 0.075
    c_flipper_left:
        number: 0-0-14
        allow_enable: true
        default_hold_power: 0.2
#!        default_pulse_power: 0.1
        default_pulse_ms: 35
    c_flipper_right:
        number: 0-0-13
        allow_enable: true
        default_hold_power: 0.2
#!        default_pulse_power: 0.54
        default_pulse_ms: 35
    c_magnet1:
       number: 0-0-12
       default_pulse_ms: 22
       default_pulse_power: 0.55
       default_hold_power: 0.075
        
switches:
    #Cabinet Switches
   s_startButton:
      number: 0-0-16
      tags: start
      ignore_window_ms: 500ms 
   s_left_flipper:
      number: 0-0-17
      tags: left_flipper
   s_right_flipper:
      number: 0-0-18
      tags: right_flipper
   s_magnet_1:
      number: 0-0-19
    #Trough Switches
   s_outhole:
      number: 1-0-40
    #Playfield Switches
 
      
flippers:
  left_flipper:
        main_coil: c_flipper_left
        activation_switch: s_left_flipper
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown
  right_flipper:
        main_coil: c_flipper_right
        activation_switch: s_right_flipper
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown



# keyboard:
#    1:
#      event: led_off
#    2:
#      event: led_code
#    3:
#      event: led_name
#    4:
#      event: group_light
#    5:
#      event: led_fade
     
ball_devices:
    bd_trough:
        ball_switches: s_outhole
        eject_coil: c_outhole
        tags: trough, home, drain, home
        eject_coil_jam_pulse: 15ms
        debug: true
    bd_magnet1:
        ball_switches: s_magnet_1
        eject_coil: c_magnet1
        eject_timeouts: 1s
        entrance_count_delay: 900ms
            
playfields:
  playfield:
    tags: default
    default_source_device: bd_trough
    enable_ball_search: True
    ball_search_timeout: 45s
    ball_search_wait_after_iteration: 30s
    ball_search_interval: 250ms

# virtual_platform_start_active_switches:
#     - s_outhole

machine:
    balls_installed: 1

game:
    balls_per_game: 3
    max_players: 4