#config_version=6

player_vars:
    pv_unbended_bananas_to_complete:
        initial_value: 10
    pv_unbended_bananas_count:
        initial_value: 0
    pv_spinner_stack_hits:
        initial_value: 0