#config_version=6

mode:
  start_events: start_mode_bumper
  stop_events: stop_mode_bumper
  priority: 200

shots:
  bumper_center:
    switch: s_bumper_done


variable_player:
  bumper_center_hit:
    score: 1_000